# Generated by Django 6.0.6 on 2026-07-29 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_changed',
            field=models.BooleanField(default=False, help_text='Whether user has changed their password after first login'),
        ),
    ]
