# Generated by Django 6.0.6 on 2026-07-29 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_password_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, help_text='Job title or position (e.g., Senior Developer, HR Manager)', max_length=100),
        ),
    ]
