# Generated by Django 6.0.6 on 2026-07-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_impersonationlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impersonationlog',
            name='session_id',
        ),
    ]
