# Generated by Django 6.0.6 on 2026-08-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='default_document_view',
            field=models.CharField(choices=[('grid', 'Grid'), ('list', 'List')], default='grid', help_text='Default view for document lists', max_length=10),
        ),
    ]
