# Generated by Django 6.0.6 on 2026-08-12 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userprofile_default_document_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional. Lets you log in with a username instead of your email.', max_length=30, null=True, unique=True),
        ),
    ]
