# Generated by Django 4.2.18 on 2026-08-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_user_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientsettings',
            name='currency_symbol',
            field=models.CharField(default='$', max_length=5),
        ),
    ]
