# Generated by Django 4.2.18 on 2026-08-30 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_user_last_seen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientsettings',
            name='currency_symbol',
        ),
    ]
