# Generated by Django 4.2.18 on 2026-08-30 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_loginhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_active_session',
            field=models.BooleanField(default=False),
        ),
    ]
