# Generated by Django 4.2.18 on 2026-08-30 17:42

from django.db import migrations, models


def backfill_first_login_flag(apps, schema_editor):
    """Mark each user's earliest existing LoginHistory row as their sign-up,
    retroactively — going forward the user_logged_in signal sets this at
    creation time, but rows recorded before this field existed all default
    to False and need a one-time correction."""
    LoginHistory = apps.get_model('accounts', 'LoginHistory')
    for user_id in LoginHistory.objects.values_list('user_id', flat=True).distinct():
        earliest = LoginHistory.objects.filter(user_id=user_id).order_by('logged_in_at').first()
        if earliest:
            earliest.is_first_login = True
            earliest.save(update_fields=['is_first_login'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_user_has_active_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='is_first_login',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_first_login_flag, migrations.RunPython.noop),
    ]
