# Generated by Django 4.2.18 on 2026-08-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_loginhistory_is_first_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginhistory',
            name='logged_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
