# Generated by Django 4.2.18 on 2026-08-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_loginhistory_logged_out_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginhistory',
            name='logged_out_at',
        ),
    ]
