# Generated by Django 4.2.18 on 2026-08-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_base', '0004_article_published_at_article_published_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='archived_from_status',
            field=models.CharField(blank=True, choices=[('DRAFT', 'Draft'), ('PENDING_REVIEW', 'Pending Review'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], max_length=20, null=True),
        ),
    ]
