# Generated by Django 6.0.6 on 2026-08-06 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_approval_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Approval',
                'verbose_name_plural': 'Organization Approvals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('DRAFT_CREATED', 'Draft Created'), ('DRAFT_UPDATED', 'Draft Updated'), ('SUBMITTED', 'Submitted for Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived'), ('RESTRUCTURED', 'Restructured')], max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Audit Log',
                'verbose_name_plural': 'Organization Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Organization Structure', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, choices=[('MARINE', 'Marine'), ('IT', 'IT'), ('ACCOUNTING', 'Accounting'), ('LEGAL', 'Legal'), ('QHSE', 'QHSE'), ('OPERATIONS', 'Operations'), ('PROJECT', 'Project'), ('VESSEL_CATERING', 'Vessel Catering'), ('PURCHASE_PROTOCOL', 'Purchase/Protocol'), ('FREIGHT', 'Freight'), ('STORE', 'Store'), ('HR', 'HR'), ('ADMIN', 'Admin'), ('COMMERCIAL', 'Commercial')], help_text='Department this org chart belongs to', max_length=30)),
                ('structure', models.JSONField(default=dict, help_text='The org chart tree structure')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending Approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('PUBLISHED', 'Published'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=20)),
                ('version', models.PositiveIntegerField(default=1)),
                ('change_summary', models.TextField(blank=True, help_text='Summary of changes made')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ManyToManyField(related_name='org_approvals', through='organogram.OrgApproval', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_drafts_created', to=settings.AUTH_USER_MODEL)),
                ('previous_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='organogram.orgdraft')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_published', to=settings.AUTH_USER_MODEL)),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='org_rejections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Organization Draft',
                'verbose_name_plural': 'Organization Drafts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrgPublished',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('structure', models.JSONField(default=dict)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('version', models.PositiveIntegerField()),
                ('department', models.CharField(blank=True, choices=[('MARINE', 'Marine'), ('IT', 'IT'), ('ACCOUNTING', 'Accounting'), ('LEGAL', 'Legal'), ('QHSE', 'QHSE'), ('OPERATIONS', 'Operations'), ('PROJECT', 'Project'), ('VESSEL_CATERING', 'Vessel Catering'), ('PURCHASE_PROTOCOL', 'Purchase/Protocol'), ('FREIGHT', 'Freight'), ('STORE', 'Store'), ('HR', 'HR'), ('ADMIN', 'Admin'), ('COMMERCIAL', 'Commercial')], max_length=30)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('draft', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='published_version', to='organogram.orgdraft')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_published_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Published Organization',
                'verbose_name_plural': 'Published Organizations',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemOrgConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('MARINE', 'Marine'), ('IT', 'IT'), ('ACCOUNTING', 'Accounting'), ('LEGAL', 'Legal'), ('QHSE', 'QHSE'), ('OPERATIONS', 'Operations'), ('PROJECT', 'Project'), ('VESSEL_CATERING', 'Vessel Catering'), ('PURCHASE_PROTOCOL', 'Purchase/Protocol'), ('FREIGHT', 'Freight'), ('STORE', 'Store'), ('HR', 'HR'), ('ADMIN', 'Admin'), ('COMMERCIAL', 'Commercial')], max_length=30, unique=True)),
                ('color', models.CharField(default='#64748B', max_length=7)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'System Org Config',
                'verbose_name_plural': 'System Org Configs',
                'ordering': ['display_order'],
            },
        ),
        migrations.DeleteModel(
            name='DepartmentConfig',
        ),
        migrations.AddField(
            model_name='orgauditlog',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='organogram.orgdraft'),
        ),
        migrations.AddField(
            model_name='orgapproval',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_approval_records', to='organogram.orgdraft'),
        ),
        migrations.DeleteModel(
            name='VacantPosition',
        ),
        migrations.AlterUniqueTogether(
            name='orgapproval',
            unique_together={('draft', 'user')},
        ),
    ]
