# Generated by Django 4.2.18 on 2026-08-22 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0002_orgapproval_orgauditlog_orgdraft_orgpublished_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgpublished',
            name='draft',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_version', to='organogram.orgdraft'),
        ),
    ]
