# Generated by Django 4.2.18 on 2026-08-24 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organogram', '0003_alter_orgpublished_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgauditlog',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='orgauditlog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='orgdraft',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='orgdraft',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='orgdraft',
            name='previous_version',
        ),
        migrations.RemoveField(
            model_name='orgdraft',
            name='published_by',
        ),
        migrations.RemoveField(
            model_name='orgdraft',
            name='rejected_by',
        ),
        migrations.RemoveField(
            model_name='orgpublished',
            name='draft',
        ),
        migrations.RemoveField(
            model_name='orgpublished',
            name='published_by',
        ),
        migrations.DeleteModel(
            name='OrgApproval',
        ),
        migrations.DeleteModel(
            name='OrgAuditLog',
        ),
        migrations.DeleteModel(
            name='OrgDraft',
        ),
        migrations.DeleteModel(
            name='OrgPublished',
        ),
    ]
