# Generated by Django 6.0.6 on 2026-07-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('TICKET', 'Ticket'), ('REMOTE_SESSION', 'Remote Session'), ('MANAGER_REVIEW', 'Manager Review'), ('APPROVAL', 'Approval'), ('RESOLUTION_CONFIRMATION', 'Resolution Confirmation')], default='GENERAL', max_length=25),
        ),
    ]
