# Generated by Django 4.2.18 on 2026-08-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_notification_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='role',
            field=models.CharField(blank=True, choices=[('SUPERADMIN', 'Super Admin'), ('ADMIN', 'Admin'), ('TEAM_LEAD', 'Team Lead'), ('AGENT', 'Support Team'), ('END_USER', 'User')], max_length=20, null=True),
        ),
    ]
