# Generated by Django 4.2.18 on 2026-08-19 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_notification_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='Lucide icon name, e.g. "book-open"', max_length=50),
        ),
    ]
