# Generated by Django 4.2.18 on 2026-08-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_drop_form_builder_tables'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read'], name='notif_recipient_is_read_idx'),
        ),
    ]
