# Generated by Django 4.2.18 on 2026-08-30 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('common', '0009_notification_notif_recipient_is_read_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('USER_MANAGEMENT', 'User Management'), ('SLA_CONFIG', 'SLA & Escalation'), ('SYSTEM_SETTINGS', 'System Settings')], max_length=20)),
                ('action', models.CharField(help_text='Short verb phrase, e.g. "Changed role", "Deleted SLA policy"', max_length=100)),
                ('target_repr', models.CharField(help_text='Human-readable label for what was affected', max_length=255)),
                ('details', models.TextField(blank=True, help_text='Freeform before/after summary')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
