# Generated by Django 6.0.6 on 2026-08-05 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0023_ticket_feedback_comment_ticket_feedback_rating_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='checked_out_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='checked_out_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checked_out_assets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='return_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='return_condition',
            field=models.CharField(blank=True, help_text='Condition of asset upon return (e.g., Good, Fair, Poor, Damaged)', max_length=50),
        ),
        migrations.AddField(
            model_name='asset',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('DISPOSAL', 'Disposal'), ('TERMINATION', 'Employee Termination'), ('SCRAPPED', 'Scrapped'), ('UPGRADED', 'Upgraded'), ('DAMAGED', 'Damaged'), ('RETURNED', 'Returned'), ('REPURPOSED', 'Repurposed'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='AssetCheckoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_out_at', models.DateTimeField()),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('checked_in_at', models.DateTimeField(blank=True, null=True)),
                ('return_reason', models.CharField(blank=True, choices=[('DISPOSAL', 'Disposal'), ('TERMINATION', 'Employee Termination'), ('SCRAPPED', 'Scrapped'), ('UPGRADED', 'Upgraded'), ('DAMAGED', 'Damaged'), ('RETURNED', 'Returned'), ('REPURPOSED', 'Repurposed'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('return_comment', models.TextField(blank=True)),
                ('return_condition', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkout_history', to='tickets.asset')),
                ('checked_in_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='checkins_initiated', to=settings.AUTH_USER_MODEL)),
                ('checked_out_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkouts_initiated', to=settings.AUTH_USER_MODEL)),
                ('checked_out_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Asset Checkout History',
                'ordering': ['-checked_out_at'],
            },
        ),
    ]
