# Generated by Django 6.0.6 on 2026-08-05 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_asset_checked_out_at_asset_checked_out_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='checked_out_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_checked_out', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='condition',
            field=models.CharField(choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged'), ('UNUSABLE', 'Unusable')], default='GOOD', max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='condition_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='current_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Current depreciated value (auto-calculated)', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='depreciation_years',
            field=models.PositiveIntegerField(default=3, help_text='Number of years over which this asset depreciates'),
        ),
        migrations.AddField(
            model_name='asset',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='last_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_interval_months',
            field=models.PositiveIntegerField(default=6, help_text='Months between scheduled maintenance'),
        ),
        migrations.AddField(
            model_name='asset',
            name='maintenance_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='next_maintenance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='po_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_order',
            field=models.CharField(blank=True, help_text='Purchase Order number', max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Purchase price in your local currency', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='returned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_returned', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='salvage_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Estimated value at end of useful life', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='scrap_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_status_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='asset',
            name='supplier',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='warranty_provider',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='assetcheckouthistory',
            name='return_condition_rating',
            field=models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged'), ('UNUSABLE', 'Unusable')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='asset_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='asset',
            name='return_condition',
            field=models.CharField(blank=True, help_text='Condition of asset upon return', max_length=50),
        ),
        migrations.AlterField(
            model_name='asset',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('DISPOSAL', 'Disposal'), ('TERMINATION', 'Employee Termination'), ('SCRAPPED', 'Scrapped'), ('UPGRADED', 'Upgraded'), ('DAMAGED', 'Damaged'), ('RETURNED', 'Returned'), ('REPURPOSED', 'Repurposed'), ('LOST', 'Lost'), ('STOLEN', 'Stolen'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(default='IN_STORE', max_length=20),
        ),
        migrations.AlterField(
            model_name='assetcheckouthistory',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('DISPOSAL', 'Disposal'), ('TERMINATION', 'Employee Termination'), ('SCRAPPED', 'Scrapped'), ('UPGRADED', 'Upgraded'), ('DAMAGED', 'Damaged'), ('RETURNED', 'Returned'), ('REPURPOSED', 'Repurposed'), ('LOST', 'Lost'), ('STOLEN', 'Stolen'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, help_text="Icon name from Lucide (e.g., 'laptop', 'monitor', 'printer')", max_length=50)),
                ('color', models.CharField(default='#64748B', help_text='Hex color code for category badge', max_length=7)),
                ('default_warranty_months', models.PositiveIntegerField(default=12)),
                ('default_depreciation_years', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tickets.assetcategory')),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='tickets.assetcategory'),
        ),
        migrations.CreateModel(
            name='AssetMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('PREVENTIVE', 'Preventive Maintenance'), ('CORRECTIVE', 'Corrective Maintenance'), ('PREDICTIVE', 'Predictive Maintenance'), ('EMERGENCY', 'Emergency Repair'), ('UPGRADE', 'Upgrade'), ('INSPECTION', 'Inspection')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('performed_at', models.DateField()),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('parts_replaced', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('next_maintenance_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='tickets.asset')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-performed_at'],
            },
        ),
    ]
