# Generated by Django 4.2.18 on 2026-08-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_asset_checked_out_by_asset_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='business_impact',
            field=models.CharField(blank=True, choices=[('FULL_OUTAGE', 'Full Outage'), ('PARTIAL_OUTAGE', 'Partial Outage'), ('DEGRADED_PERFORMANCE', 'Degraded Performance'), ('NO_IMPACT', 'No Immediate Impact')], max_length=25),
        ),
        migrations.AddField(
            model_name='ticket',
            name='how_discovered',
            field=models.CharField(blank=True, choices=[('MONITORING_ALERT', 'Monitoring Tool / Alert'), ('USER_COMPLAINT', 'User Complaint'), ('ROUTINE_CHECK', 'Routine Check'), ('EXTERNAL_NOTIFICATION', 'External Notification'), ('OTHER', 'Other')], max_length=25),
        ),
        migrations.AddField(
            model_name='ticket',
            name='how_discovered_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='immediate_actions',
            field=models.TextField(blank=True, help_text='Immediate/initial actions taken at the time of the incident'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='incident_category',
            field=models.CharField(blank=True, choices=[('HARDWARE_FAILURE', 'Hardware Failure'), ('SOFTWARE_ERROR', 'Software / Application Error'), ('NETWORK_CONNECTIVITY', 'Network / Connectivity'), ('SECURITY_BREACH', 'Security Breach / Unauthorized Access'), ('DATA_LOSS', 'Data Loss / Corruption'), ('POWER_FAILURE', 'Power Failure'), ('OTHER', 'Other')], max_length=25),
        ),
        migrations.AddField(
            model_name='ticket',
            name='incident_category_other',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='ticket',
            name='incident_datetime',
            field=models.DateTimeField(blank=True, help_text='When the incident actually started', null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='location_hostname',
            field=models.CharField(blank=True, help_text='Location / IP address / hostname, if known', max_length=200),
        ),
    ]
