# Generated by Django 4.2.18 on 2026-08-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_servicecategory_vessel_ticket_purpose_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='macro',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('INTERNAL', 'Internal'), ('PRIVATE', 'Private (only me)')], default='PUBLIC', max_length=10),
        ),
    ]
