# Generated by Django 4.2.18 on 2026-08-17 18:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0031_ticket_submission_latitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mobilization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('mobilized_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expected_return_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('dive_spreads', models.ManyToManyField(blank=True, related_name='mobilizations', to='tickets.divespread')),
                ('job_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mobilizations', to='tickets.jobnumber')),
                ('mobilized_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobilizations_initiated', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilizations', to='tickets.ticket')),
                ('vessels', models.ManyToManyField(blank=True, related_name='mobilizations', to='tickets.vessel')),
            ],
            options={
                'ordering': ['-mobilized_at'],
            },
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned'), ('STATUS_CHANGED', 'Status Changed'), ('SCRAP_REQUESTED', 'Scrap Requested'), ('SCRAP_APPROVED', 'Scrap Approved'), ('SCRAP_REJECTED', 'Scrap Rejected'), ('MOBILIZED', 'Mobilized'), ('DEMOBILIZED', 'Demobilized')], max_length=20),
        ),
        migrations.CreateModel(
            name='MobilizationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demobilized_at', models.DateTimeField(blank=True, null=True)),
                ('return_condition', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('POOR', 'Poor'), ('DAMAGED', 'Damaged'), ('UNUSABLE', 'Unusable')], max_length=20, null=True)),
                ('return_notes', models.TextField(blank=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobilization_items', to='tickets.asset')),
                ('demobilized_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='demobilizations_initiated', to=settings.AUTH_USER_MODEL)),
                ('mobilization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='tickets.mobilization')),
            ],
            options={
                'ordering': ['-mobilization__mobilized_at'],
            },
        ),
    ]
