# Generated by Django 4.2.18 on 2026-08-17 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0032_mobilization_alter_assetlog_action_mobilizationitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='asset_type',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='current_value',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='depreciation_years',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='invoice_number',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='last_maintenance',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='maintenance_interval_months',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='maintenance_notes',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='next_maintenance',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='po_number',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='salvage_value',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='supplier',
        ),
    ]
