# Generated by Django 4.2.18 on 2026-08-18 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0033_remove_asset_asset_type_remove_asset_current_value_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='resolution_root_cause',
            field=models.TextField(blank=True, help_text='Root cause identified by the resolving agent'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_steps',
            field=models.TextField(blank=True, help_text='Steps taken by the resolving agent to fix the issue'),
        ),
    ]
