# Generated by Django 4.2.18 on 2026-08-18 08:52

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0034_ticket_resolution_root_cause_ticket_resolution_steps'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='incident_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='incident_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_root_cause_category',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('HUMAN_ERROR', 'Human Error'), ('CONFIGURATION_ERROR', 'Configuration Error'), ('SOFTWARE_BUG', 'Software Bug / Patch Issue'), ('HARDWARE_FAILURE', 'Hardware Failure'), ('CYBER_ATTACK', 'Cyber Attack / Malware'), ('POWER_INFRASTRUCTURE_FAILURE', 'Power / Infrastructure Failure'), ('VENDOR_THIRD_PARTY', 'Vendor / Third-Party Issue'), ('CHANGE_MANAGEMENT_FAILURE', 'Change Management Failure'), ('UNKNOWN', 'Unknown')], max_length=30), blank=True, default=list, help_text='Root cause categories ticked by the resolving agent', size=None),
        ),
    ]
