# Generated by Django 4.2.18 on 2026-08-18 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0035_ticket_incident_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='department',
            field=models.CharField(blank=True, choices=[('MARINE', 'Marine'), ('IT', 'IT'), ('ACCOUNTING', 'Accounting'), ('LEGAL', 'Legal'), ('QHSE', 'QHSE'), ('OPERATIONS', 'Operations'), ('PROJECT', 'Project'), ('VESSEL_CATERING', 'Vessel Catering'), ('PURCHASE_PROTOCOL', 'Purchase/Protocol'), ('FREIGHT', 'Freight'), ('STORE', 'Store'), ('HR', 'HR'), ('ADMIN', 'Admin'), ('COMMERCIAL', 'Commercial')], max_length=30),
        ),
    ]
