# Generated by Django 4.2.18 on 2026-08-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0038_vessel_proposed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='is_consumable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mobilizationitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='mobilizationitem',
            name='return_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
