# Generated by Django 4.2.18 on 2026-08-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0039_consumable_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='low_stock_notified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
