# Generated by Django 4.2.18 on 2026-08-19 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_add_vendor'),
        ('tickets', '0041_assetprocurementrequest_asset_procurement_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='auto_renews',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='next_renewal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='renewal_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='renewal_interval_months',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='renewal_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='asset',
            name='renewal_reminder_30d_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='renewal_reminder_7d_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='renewal_reminder_90d_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asset',
            name='renewal_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_renewals', to='maintenance.vendor'),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='is_renewable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned'), ('STATUS_CHANGED', 'Status Changed'), ('SCRAP_REQUESTED', 'Scrap Requested'), ('SCRAP_APPROVED', 'Scrap Approved'), ('SCRAP_REJECTED', 'Scrap Rejected'), ('MOBILIZED', 'Mobilized'), ('DEMOBILIZED', 'Demobilized'), ('RENEWED', 'Renewed')], max_length=20),
        ),
    ]
