# Generated by Django 4.2.18 on 2026-08-20 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def backfill_original_expected_return_date(apps, schema_editor):
    """Existing Mobilization rows predate original_expected_return_date —
    snapshot their current expected_return_date as the original so history
    doesn't start blank for pre-existing jobs."""
    Mobilization = apps.get_model('tickets', 'Mobilization')
    Mobilization.objects.filter(original_expected_return_date__isnull=True).update(
        original_expected_return_date=models.F('expected_return_date')
    )


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0042_asset_auto_renews_asset_next_renewal_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobilizationDateExtension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_date', models.DateField(blank=True, null=True)),
                ('new_date', models.DateField()),
                ('reason', models.TextField(blank=True)),
                ('extended_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-extended_at'],
            },
        ),
        migrations.AddField(
            model_name='mobilization',
            name='original_expected_return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_original_expected_return_date, migrations.RunPython.noop),
        migrations.AddField(
            model_name='ticket',
            name='is_mobilization_request',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['status', 'is_mobilization_request'], name='tickets_tic_status_ab0fed_idx'),
        ),
        migrations.AddField(
            model_name='mobilizationdateextension',
            name='extended_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mobilization_extensions_made', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilizationdateextension',
            name='mobilization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_extensions', to='tickets.mobilization'),
        ),
    ]
