# Generated by Django 4.2.18 on 2026-08-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0043_mobilizationdateextension_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='preview_pdf',
            field=models.FileField(blank=True, null=True, upload_to='attachments/previews/%Y/%m/%d/'),
        ),
    ]
