# Generated by Django 4.2.18 on 2026-08-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0044_attachment_preview_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('ORDERED', 'Ordered'), ('RECEIVED', 'Received'), ('IN_STORE', 'In Store'), ('READY', 'Ready for Deployment'), ('CHECKED_OUT', 'Checked Out'), ('IN_USE', 'In Use'), ('MOBILIZED', 'Mobilized'), ('MAINTENANCE', 'Maintenance'), ('REPAIR', 'Repair'), ('DAMAGED', 'Damaged'), ('RETURNED', 'Returned'), ('RETIRED', 'Retired'), ('SCRAPPED', 'Scrapped'), ('LOST', 'Lost'), ('STOLEN', 'Stolen'), ('DISPOSED', 'Disposed')], default='IN_STORE', max_length=20),
        ),
    ]
