# Generated by Django 4.2.18 on 2026-08-24 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0045_alter_asset_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetcheckouthistory',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcheckouthistory',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_checkouts_acknowledged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetcheckouthistory',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assetcheckouthistory',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcheckouthistory',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetcheckouthistory',
            name='return_requested_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='assetcheckouthistory',
            name='return_requested_reason',
            field=models.CharField(blank=True, choices=[('DISPOSAL', 'Disposal'), ('TERMINATION', 'Employee Termination'), ('SCRAPPED', 'Scrapped'), ('UPGRADED', 'Upgraded'), ('DAMAGED', 'Damaged'), ('RETURNED', 'Returned'), ('REPURPOSED', 'Repurposed'), ('LOST', 'Lost'), ('STOLEN', 'Stolen'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
    ]
