# Generated by Django 4.2.18 on 2026-08-25 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0046_assetcheckouthistory_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='renewal_reminder_overdue_last_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assetlog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('ASSIGNED', 'Assigned'), ('UNASSIGNED', 'Unassigned'), ('STATUS_CHANGED', 'Status Changed'), ('SCRAP_REQUESTED', 'Scrap Requested'), ('SCRAP_APPROVED', 'Scrap Approved'), ('SCRAP_REJECTED', 'Scrap Rejected'), ('MOBILIZED', 'Mobilized'), ('DEMOBILIZED', 'Demobilized'), ('RENEWED', 'Renewed'), ('STOCK_ADJUSTED', 'Stock Adjusted')], max_length=20),
        ),
        migrations.CreateModel(
            name='AssetAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='asset_attachments/%Y/%m/%d/')),
                ('filename', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size', models.PositiveIntegerField(default=0)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.asset')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
