# Generated by Django 4.2.18 on 2026-08-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0047_asset_renewal_reminder_overdue_last_sent_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='assetprocurementrequest',
            constraint=models.CheckConstraint(check=models.Q(('ticket__isnull', True), ('mobilization__isnull', True), _connector='OR'), name='procurement_request_not_both_ticket_and_mobilization'),
        ),
    ]
