# Generated by Django 4.2.18 on 2026-08-26 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0048_assetprocurementrequest_procurement_request_not_both_ticket_and_mobilization'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilizationitem',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilizationitem',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilization_items_acknowledged', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilizationitem',
            name='dispute_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mobilizationitem',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
