# Generated by Django 4.2.18 on 2026-08-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0049_mobilizationitem_acknowledged_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='is_receipt_confirmation_prompt',
            field=models.BooleanField(default=False),
        ),
    ]
