# Generated by Django 4.2.18 on 2026-08-26 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0050_ticketcomment_is_receipt_confirmation_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='mobilization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to='tickets.mobilization'),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='mobilization_event',
            field=models.CharField(blank=True, choices=[('CREATED', 'Created'), ('VENDOR_ITEM_ARRIVED', 'Vendor Item Arrived'), ('VENDOR_ITEM_CANCELLED', 'Vendor Item Cancelled')], max_length=25),
        ),
    ]
