# Generated by Django 4.2.18 on 2026-08-26 14:44

from django.db import migrations, models
from django.db.models import Q


def backfill_is_system_generated(apps, schema_editor):
    """Every existing comment already identifiable as system-composed via
    is_receipt_confirmation_prompt or mobilization_event is unambiguously
    a system card — flip the new display flag for those retroactively so
    already-posted mobilization/receipt-confirmation cards immediately
    show "System" instead of the triggering admin's name. This is safe to
    backfill (unlike comment body text) since it's a pure display flag,
    not baked-in frozen text."""
    TicketComment = apps.get_model('tickets', 'TicketComment')
    TicketComment.objects.filter(
        Q(is_receipt_confirmation_prompt=True) | ~Q(mobilization_event='')
    ).update(is_system_generated=True)


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0051_ticketcomment_mobilization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='is_system_generated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='system_icon',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.RunPython(backfill_is_system_generated, migrations.RunPython.noop),
    ]
