# Generated by Django 4.2.18 on 2026-08-26 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0052_ticketcomment_is_system_generated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobilizationitem',
            name='return_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobilizationitem',
            name='return_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mobilization_items_return_requested', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mobilizationitem',
            name='return_requested_notes',
            field=models.TextField(blank=True),
        ),
    ]
