# Generated by Django 4.2.18 on 2026-08-27 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0062_remove_asset_assigned_to_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcomment',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
