# Generated by Django 4.2.18 on 2026-08-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0063_alter_ticketcomment_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='unresolved_assignee_hint',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
    ]
