# Generated by Django 4.2.18 on 2026-08-30 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0064_asset_unresolved_assignee_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='renewal_currency',
            field=models.CharField(blank=True, default='$', max_length=5),
        ),
    ]
