# Generated by Django 4.2.18 on 2026-08-30 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0065_asset_renewal_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='renewal_currency',
            field=models.CharField(blank=True, choices=[('$', '$ USD'), ('€', '€ EUR'), ('£', '£ GBP'), ('₦', '₦ NGN'), ('₹', '₹ INR')], default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='asset',
            name='renewal_interval_months',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (4, '4 Months'), (5, '5 Months'), (6, '6 Months'), (12, '12 Months (Annual)')], null=True),
        ),
    ]
