# Generated by Django 4.2.18 on 2026-08-30 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0067_asset_status_cleanup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicecategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Service categories'},
        ),
        migrations.RemoveField(
            model_name='servicecategory',
            name='order',
        ),
    ]
