# Generated by Django 4.2.18 on 2026-09-02 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0070_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='is_rejection_prompt',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ticketcomment',
            name='is_revision_request_prompt',
            field=models.BooleanField(default=False),
        ),
    ]
