# Generated by Django 4.2.18 on 2026-09-06 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0071_ticketcomment_is_rejection_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='first_assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='resolution_paused_minutes',
            field=models.FloatField(default=0),
        ),
    ]
