# Generated by Django 4.2.18 on 2026-09-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0072_ticket_first_assigned_at_ticket_resolution_paused_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='is_resolution_confirmation_prompt',
            field=models.BooleanField(default=False),
        ),
    ]
