# Generated by Django 4.2.18 on 2026-09-07 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0073_ticketcomment_is_resolution_confirmation_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcomment',
            name='remote_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_comments', to='tickets.remotesession'),
        ),
    ]
