# Generated by Django 6.0.6 on 2026-08-05 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(choices=[('MARINE', 'Marine'), ('IT', 'IT'), ('ACCOUNTING', 'Accounting'), ('LEGAL', 'Legal'), ('QHSE', 'QHSE'), ('OPERATIONS', 'Operations'), ('PROJECT', 'Project'), ('VESSEL_CATERING', 'Vessel Catering'), ('PURCHASE_PROTOCOL', 'Purchase/Protocol'), ('FREIGHT', 'Freight'), ('STORE', 'Store'), ('HR', 'HR'), ('ADMIN', 'Admin'), ('COMMERCIAL', 'Commercial')], max_length=30)),
                ('scheduled_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=20)),
                ('checklist_items', models.JSONField(blank=True, default=list)),
                ('completed_checklist', models.JSONField(blank=True, default=list)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_comment', models.TextField(blank=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('email_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_maintenance', to=settings.AUTH_USER_MODEL)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_maintenance', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Schedule',
                'verbose_name_plural': 'Maintenance Schedules',
                'ordering': ['-scheduled_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('STATUS_CHANGED', 'Status Changed'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('EMAIL_SENT', 'Email Sent')], max_length=20)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='maintenance.maintenanceschedule')),
            ],
            options={
                'verbose_name': 'Maintenance Activity Log',
                'verbose_name_plural': 'Maintenance Activity Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['department', 'status'], name='maintenance_departm_651db4_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['scheduled_date'], name='maintenance_schedul_003ebc_idx'),
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['assigned_to', 'status'], name='maintenance_assigne_9e2534_idx'),
        ),
    ]
