# Generated by Django 6.0.6 on 2026-08-12 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='additional_assignees',
            field=models.ManyToManyField(blank=True, related_name='additional_maintenance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='reminder_10m_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='reminder_1h_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='reminder_24h_sent',
            field=models.BooleanField(default=False),
        ),
    ]
