# Generated by Django 4.2.18 on 2026-08-18 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tickets', '0034_ticket_resolution_root_cause_ticket_resolution_steps'),
        ('maintenance', '0002_maintenanceschedule_additional_assignees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='facility_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='target_assets',
            field=models.ManyToManyField(blank=True, related_name='maintenance_schedules', to='tickets.asset'),
        ),
        migrations.CreateModel(
            name='MaintenanceChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('MARINE', 'Marine'), ('IT', 'IT'), ('ACCOUNTING', 'Accounting'), ('LEGAL', 'Legal'), ('QHSE', 'QHSE'), ('OPERATIONS', 'Operations'), ('PROJECT', 'Project'), ('VESSEL_CATERING', 'Vessel Catering'), ('PURCHASE_PROTOCOL', 'Purchase/Protocol'), ('FREIGHT', 'Freight'), ('STORE', 'Store'), ('HR', 'HR'), ('ADMIN', 'Admin'), ('COMMERCIAL', 'Commercial')], max_length=30)),
                ('text', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Maintenance Checklist Item',
                'verbose_name_plural': 'Maintenance Checklist Items',
                'ordering': ['department', 'order', 'text'],
                'indexes': [models.Index(fields=['department', 'is_active'], name='maintenance_departm_b1e4cd_idx')],
            },
        ),
    ]
