# Generated by Django 4.2.18 on 2026-08-18 23:33, hand-edited to preserve
# existing single-department data when migrating to the new multi-value
# `departments` field (see apps/maintenance/models.py).

import django.contrib.postgres.fields
from django.db import migrations, models


def copy_department_to_departments(apps, schema_editor):
    MaintenanceSchedule = apps.get_model('maintenance', 'MaintenanceSchedule')
    for schedule in MaintenanceSchedule.objects.exclude(department=''):
        schedule.departments = [schedule.department]
        schedule.save(update_fields=['departments'])


def copy_departments_to_department(apps, schema_editor):
    MaintenanceSchedule = apps.get_model('maintenance', 'MaintenanceSchedule')
    for schedule in MaintenanceSchedule.objects.exclude(departments=[]):
        schedule.department = schedule.departments[0]
        schedule.save(update_fields=['department'])


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_backfill_completed_checklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='departments',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('MARINE', 'Marine'), ('IT', 'IT'), ('ACCOUNTING', 'Accounting'), ('LEGAL', 'Legal'), ('QHSE', 'QHSE'), ('OPERATIONS', 'Operations'), ('PROJECT', 'Project'), ('VESSEL_CATERING', 'Vessel Catering'), ('PURCHASE_PROTOCOL', 'Purchase/Protocol'), ('FREIGHT', 'Freight'), ('STORE', 'Store'), ('HR', 'HR'), ('ADMIN', 'Admin'), ('COMMERCIAL', 'Commercial')], max_length=30), blank=True, default=list, size=None),
        ),
        migrations.RunPython(copy_department_to_departments, copy_departments_to_department),
        migrations.RemoveIndex(
            model_name='maintenanceschedule',
            name='maintenance_departm_651db4_idx',
        ),
        migrations.RemoveField(
            model_name='maintenanceschedule',
            name='department',
        ),
        migrations.AddIndex(
            model_name='maintenanceschedule',
            index=models.Index(fields=['status'], name='maintenance_status_b17e4a_idx'),
        ),
    ]
