# Generated by Django 4.2.18 on 2026-08-20 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0042_asset_auto_renews_asset_next_renewal_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0006_add_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceactivitylog',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('STATUS_CHANGED', 'Status Changed'), ('ASSIGNED', 'Assigned'), ('COMPLETED', 'Completed'), ('CONFIRMED', 'Confirmed'), ('DISPUTED', 'Disputed'), ('CANCELLED', 'Cancelled'), ('EMAIL_SENT', 'Email Sent')], max_length=20),
        ),
        migrations.CreateModel(
            name='MaintenanceAssetConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('DISPUTED', 'Disputed')], default='PENDING', max_length=20)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('dispute_reason', models.TextField(blank=True)),
                ('technician_completed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmation_reminder_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_confirmations', to='tickets.asset')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_confirmations', to='maintenance.maintenanceschedule')),
            ],
            options={
                'verbose_name': 'Maintenance Asset Confirmation',
                'verbose_name_plural': 'Maintenance Asset Confirmations',
                'ordering': ['asset__name'],
                'indexes': [models.Index(fields=['status'], name='maintenance_status_15324d_idx'), models.Index(fields=['confirmation_reminder_sent'], name='maintenance_confirm_b0748d_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='maintenanceassetconfirmation',
            constraint=models.UniqueConstraint(fields=('schedule', 'asset'), name='unique_schedule_asset_confirmation'),
        ),
    ]
