# Generated by Django 4.2.18 on 2026-08-20 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0043_mobilizationdateextension_and_more'),
        ('maintenance', '0007_alter_maintenanceactivitylog_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='vendors', to='tickets.assetcategory'),
        ),
    ]
