# Generated by Django 4.2.18 on 2026-08-25 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0008_vendor_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='proposed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proposed_vendors', to=settings.AUTH_USER_MODEL),
        ),
    ]
