# Generated by Django 4.2.18 on 2026-08-27 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_assetbackupstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
