# Generated by Django 4.2.18 on 2026-08-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_maintenanceschedule_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceschedule',
            name='next_occurrence_created',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='maintenanceschedule',
            name='repeat_interval',
            field=models.CharField(choices=[('NONE', 'Does not repeat'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Every 2 weeks'), ('MONTHLY', 'Monthly')], default='NONE', max_length=10),
        ),
    ]
