# Generated by Django 4.2.18 on 2026-08-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0012_maintenanceschedule_next_occurrence_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceschedule',
            name='repeat_interval',
            field=models.CharField(blank=True, choices=[('NONE', 'Does not repeat'), ('WEEKLY', 'Weekly'), ('BIWEEKLY', 'Every 2 weeks'), ('MONTHLY', 'Monthly')], default='NONE', max_length=10),
        ),
    ]
