# Generated by Django 6.0.6 on 2026-08-06 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('SERVICE_REQUEST', 'Service Request'), ('INCIDENT', 'Incident'), ('MOBILIZATION', 'Job Mobilization'), ('RETURN', 'Job Return'), ('SURVEY', 'Survey'), ('INSPECTION', 'Inspection'), ('FEEDBACK', 'Feedback'), ('OTHER', 'Other')], max_length=50)),
                ('schema', models.JSONField(default=dict, help_text='Template form schema')),
                ('icon', models.CharField(default='📝', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='logo_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='max_submissions',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='submission_limit_per_user',
            field=models.PositiveIntegerField(default=0, help_text='0 = unlimited'),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='template_type',
            field=models.CharField(choices=[('BLANK', 'Blank Form'), ('CONTACT', 'Contact Form'), ('INCIDENT_REPORT', 'Incident Report'), ('JOB_MOBILIZATION', 'Job Mobilization'), ('EMPLOYEE_ONBOARDING', 'Employee Onboarding'), ('FEEDBACK', 'Feedback Form'), ('SURVEY', 'Survey')], default='BLANK', max_length=30),
        ),
        migrations.AddField(
            model_name='formdefinition',
            name='theme_color',
            field=models.CharField(default='#0D9488', help_text='Primary color for form', max_length=7),
        ),
        migrations.AlterField(
            model_name='formdefinition',
            name='form_type',
            field=models.CharField(choices=[('SERVICE_REQUEST', 'Service Request'), ('INCIDENT', 'Incident'), ('MOBILIZATION', 'Job Mobilization'), ('RETURN', 'Job Return'), ('SURVEY', 'Survey'), ('INSPECTION', 'Inspection'), ('FEEDBACK', 'Feedback'), ('OTHER', 'Other')], default='OTHER', max_length=20),
        ),
    ]
