# Generated by Django 6.0.6 on 2026-08-09 15:06

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_display', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='displaydocument',
            name='content',
        ),
        migrations.RemoveField(
            model_name='displaydocument',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='displayversion',
            name='content',
        ),
        migrations.AlterField(
            model_name='displaydocument',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='display_docs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx', 'txt', 'csv', 'zip', 'png', 'jpg', 'jpeg', 'gif', 'webp'])]),
            preserve_default=False,
        ),
    ]
