# Generated by Django 6.0.6 on 2026-08-09 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_display', '0002_remove_displaydocument_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaydocument',
            name='preview_pdf',
            field=models.FileField(blank=True, help_text='Automatically generated PDF preview for Office documents', null=True, upload_to='display_docs/previews/%Y/%m/%d/'),
        ),
    ]
