# Generated by Django 6.0.6 on 2026-08-09 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_display', '0003_displaydocument_preview_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='displaydocument',
            name='allowed_departments',
            field=models.JSONField(blank=True, default=list, help_text='List of department codes (only used when visibility is RESTRICTED)'),
        ),
        migrations.AddField(
            model_name='displaydocument',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public (All Users)'), ('DEPARTMENT', 'Department Only'), ('RESTRICTED', 'Restricted (Specific Departments)')], default='PUBLIC', max_length=20),
        ),
    ]
