# Generated by Django 6.0.6 on 2026-08-10 11:18
# Hand-split: additive schema only (safe, zero-downtime). Field removal and
# visibility-choice cleanup are deferred to 0007, after the 0006 backfill.

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_display', '0004_displaydocument_allowed_departments_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='displaydocument',
            name='downloaders',
            field=models.ManyToManyField(blank=True, help_text='Per-user download override, independent of department grants', related_name='downloadable_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='displaydocument',
            name='public_can_download',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='displaydocument',
            name='public_can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='displaydocument',
            name='editors',
            field=models.ManyToManyField(blank=True, help_text='Per-user edit override, independent of department grants', related_name='editable_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='DocumentDepartmentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('MARINE', 'Marine'), ('IT', 'IT'), ('ACCOUNTING', 'Accounting'), ('LEGAL', 'Legal'), ('QHSE', 'QHSE'), ('OPERATIONS', 'Operations'), ('PROJECT', 'Project'), ('VESSEL_CATERING', 'Vessel Catering'), ('PURCHASE_PROTOCOL', 'Purchase/Protocol'), ('FREIGHT', 'Freight'), ('STORE', 'Store'), ('HR', 'HR'), ('ADMIN', 'Admin'), ('COMMERCIAL', 'Commercial')], max_length=30)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_download', models.BooleanField(default=False)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_access', to='documents_display.displaydocument')),
            ],
            options={
                'verbose_name_plural': 'Document department access',
                'indexes': [models.Index(fields=['department'], name='documents_d_departm_8732a8_idx')],
                'unique_together': {('document', 'department')},
            },
        ),
    ]
