# Generated by Django 6.0.6 on 2026-08-12 12:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents_display', '0008_documentshare'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentshare',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='documentshare',
            name='expires_at',
            field=models.DateTimeField(blank=True, help_text='Optional. Required for external shares.', null=True),
        ),
        migrations.AddField(
            model_name='documentshare',
            name='external_email',
            field=models.EmailField(blank=True, help_text='For sharing with someone outside the organization - no account required.', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='documentshare',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='documentshare',
            constraint=models.UniqueConstraint(condition=models.Q(('recipient__isnull', False)), fields=('document', 'recipient'), name='uniq_document_recipient_share'),
        ),
        migrations.AddConstraint(
            model_name='documentshare',
            constraint=models.UniqueConstraint(condition=models.Q(('external_email__isnull', False)), fields=('document', 'external_email'), name='uniq_document_external_email_share'),
        ),
        migrations.AddConstraint(
            model_name='documentshare',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('external_email__isnull', True), ('recipient__isnull', False)), models.Q(('external_email__isnull', False), ('recipient__isnull', True)), _connector='OR'), name='document_share_exactly_one_target'),
        ),
    ]
