# Generated by Django 4.2.18 on 2026-08-18 16:36

import apps.documents_display.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents_display', '0009_alter_documentshare_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='document_folders_created', to=settings.AUTH_USER_MODEL)),
                ('documents', models.ManyToManyField(blank=True, related_name='folders', to='documents_display.displaydocument')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='FolderShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_email', models.EmailField(blank=True, help_text='For sharing with someone outside the organization - no account required.', max_length=254, null=True)),
                ('can_download', models.BooleanField(default=False)),
                ('token', models.CharField(default=apps.documents_display.models.generate_share_token, max_length=64, unique=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Optional. Required for external shares.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, help_text='First time the recipient opened the emailed link', null=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='documents_display.documentfolder')),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_shares', to=settings.AUTH_USER_MODEL)),
                ('shared_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='foldershare',
            constraint=models.UniqueConstraint(condition=models.Q(('recipient__isnull', False)), fields=('folder', 'recipient'), name='uniq_folder_recipient_share'),
        ),
        migrations.AddConstraint(
            model_name='foldershare',
            constraint=models.UniqueConstraint(condition=models.Q(('external_email__isnull', False)), fields=('folder', 'external_email'), name='uniq_folder_external_email_share'),
        ),
        migrations.AddConstraint(
            model_name='foldershare',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('external_email__isnull', True), ('recipient__isnull', False)), models.Q(('external_email__isnull', False), ('recipient__isnull', True)), _connector='OR'), name='folder_share_exactly_one_target'),
        ),
    ]
