# Generated by Django 4.2.18 on 2026-08-28 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents_display', '0010_documentfolder_foldershare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentshare',
            name='expiry_reminder_sent',
            field=models.BooleanField(default=False, help_text='Set once send_share_expiry_reminders has notified the sharer this grant is about to expire.'),
        ),
        migrations.AddField(
            model_name='foldershare',
            name='expiry_reminder_sent',
            field=models.BooleanField(default=False, help_text='Set once send_share_expiry_reminders has notified the sharer this grant is about to expire.'),
        ),
        migrations.CreateModel(
            name='ShareAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('event', models.CharField(choices=[('CREATED', 'Created'), ('EMAIL_SENT', 'Email sent'), ('EMAIL_FAILED', 'Email failed'), ('OPENED', 'Link opened'), ('VIEWED', 'File viewed'), ('DOWNLOADED', 'File downloaded'), ('REVOKED', 'Revoked'), ('EXPIRY_REMINDER_SENT', 'Expiry reminder sent')], max_length=30)),
                ('detail', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Who triggered this event, if a logged-in user did (blank for token-based external actions).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id', '-created_at'], name='documents_d_content_266f89_idx')],
            },
        ),
    ]
